### ISSUE TITLE
No exports from this package

### ISSUE THREAD

**Issue by JoshuaDPitts** [ellipsis-drive-internal/mapboxgljs-package#3]
following the install commands, 
npm install mapboxgljs-ellipsis
and yarn add mapboxgljs-ellipsis
both do not install and build the library. 

Can be reproduced with a clean install:
> npm init
> npm install mapboxgljs-ellipsis

there is no index.js in node_modules/mapboxgljs-ellipsis

**Comment by danielvandermaas** [comment]
I think in the latest release the build was not included. I made a fix for this can you check you can install version 3.1.3 now?

**Comment by JoshuaDPitts** [comment]
@danielvandermaas , the main export looks to be working now. However, some of the exports are still not resolving fully. This one is not resolving correctly:
`import MapboxgljsEllipsis from 'mapboxgljs-ellipsis';
...
new MapboxgljsEllipsis.MapboxgljsEllipsis.EllipsisVectorLayer({
                "pathID":"...",
                token: "..."
            }).addTo(map);
`
I think that EllipsisVectorLayer is not being indexed in the build correctly, but perhaps my usage is wrong in the react app

**Comment by danielvandermaas** [comment]
You can import the required functions as follows
`import {
	EllipsisVectorLayer,
	EllipsisRasterLayer,
	AsyncEllipsisRasterLayer,
} from 'mapboxgljs-ellipsis';
`
